# Generated by Django 2.2.6 on 2019-10-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Number', models.IntegerField()),
                ('Address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField()),
                ('Type', models.CharField(max_length=20)),
                ('Bed', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guests', models.IntegerField()),
                ('date_of_book', models.DateField()),
                ('date_of_cancel', models.DateField(blank=True, null=True)),
                ('Check_IN', models.DateField()),
                ('Check_OUT', models.DateField()),
                ('Invoice', models.IntegerField(default=0)),
                ('Available', models.BooleanField()),
                ('Guest_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Guest')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelapp.Room')),
            ],
        ),
    ]
