# Generated by Django 2.2.6 on 2019-10-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
