# Generated by Django 2.2.6 on 2019-10-19 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_auto_20191019_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_book',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 9, 33, 52, 155705)),
        ),
    ]
