# Generated by Django 2.2.6 on 2019-10-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0002_booking_checked_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Available',
        ),
    ]
