# Generated by Django 2.2.6 on 2019-10-19 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_auto_20191019_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_book',
            field=models.DateField(default=datetime.datetime(2019, 10, 19, 9, 34, 55, 17375)),
        ),
    ]
