# Generated by Django 2.2.6 on 2019-10-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_remove_booking_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
