# Generated by Django 2.2.6 on 2019-10-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_auto_20191019_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date_of_book',
            field=models.DateField(),
        ),
    ]
