# Generated by Django 2.2.6 on 2019-10-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_remove_booking_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Type',
            new_name='Room_Number',
        ),
    ]
