# Generated by Django 2.2.6 on 2019-10-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0007_auto_20191019_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_stay_days',
            field=models.IntegerField(default=1),
        ),
    ]
